HotelBooking.WEB/Controllers/RoomTypesManagerController.cs
using HotelBooking.Domain.Request.HotelServices;
using HotelBooking.Domain.Response;
using HotelBooking.Domain.Response.HotelServices;
using HotelBooking.Web.Ultilities;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace HotelBooking.WEB.Controllers
{
    public class RoomTypesManagerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public JsonResult GetAll()
        {
            List<RoomType> result = ApiHelper<List<RoomType>>.HttpGetAsync($"{Helper.ApiUrl}api/roomtypes/getall");
            return Json(new { result });
        }

        public JsonResult GetAllWithImages()
        {
            List<RoomTypes> result = ApiHelper<List<RoomTypes>>.HttpGetAsync($"{Helper.ApiUrl}api/roomtypes/getallroomtypewithimages");
            return Json(new { result });
        }

        public JsonResult GetAllWithImagesAndFacilities()
        {
            List<RoomTypes> result = ApiHelper<List<RoomTypes>>.HttpGetAsync($"{Helper.ApiUrl}api/roomtypes/getallroomtypewithimagesandfacilities");
            return Json(new { result });
        }

        public JsonResult Get(int id)
        {
            RoomType result = ApiHelper<RoomType>.HttpGetAsync($"{Helper.ApiUrl}api/roomtypes/getbyid/{id}");
            return Json(new { result });
        }

        public JsonResult GetWithImagesAndFacilities(int id)
        {
            RoomType result = ApiHelper<RoomType>.HttpGetAsync($"{Helper.ApiUrl}api/roomtypes/getbyidwithimagesandfacilities/{id}");
            return Json(new { result });
        }

        public JsonResult Delete(int id)
        {
            ActionsResult result = ApiHelper<ActionsResult>.HttpGetAsync($"{Helper.ApiUrl}api/roomtypes/delete/{id}", "DELETE");
            return Json(new { result });
        }

        public JsonResult Save([FromBody] CreateRoomTypeRequest model)
        {
            ActionsResult result;
            result = ApiHelper<ActionsResult>.HttpPostAsync($"{Helper.ApiUrl}api/roomtypes/save", model);
            return Json(new { result });
        }

        public JsonResult Search([FromBody] SearchRoomTypesRequest model)
        {
            var result = ApiHelper<List<RoomTypeSearchResult>>.HttpPostAsync($"{Helper.ApiUrl}api/roomtypes/search", model);
            return Json(new { result });
        }
    }
}

HotelBooking.WEB/Controllers/RoomsController.cs
using Microsoft.AspNetCore.Mvc;

namespace HotelBooking.WEB.Controllers
{
    public class RoomsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            return View(id);
        }
    }
}

HotelBooking.WEB/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;

namespace HotelBooking.WEB.Controllers
{
    public class ServicesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HotelBooking.WEB/Controllers/UserController.cs
using HotelBooking.Domain.Request.Account;
using HotelBooking.Domain.Response.Account;
using HotelBooking.Web.Ultilities;
using Microsoft.AspNetCore.Mvc;

namespace HotelBooking.WEB.Controllers
{
    public class UserController : Controller
    {
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var loginRequest = new LoginRequest()
                {
                    Email = model.Email,
                    Password = model.Password
                };
                LoginResult result = ApiHelper<LoginResult>.HttpPostAsync($"{Helper.ApiUrl}api/account/login", loginRequest);
                if (result.Success)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", result.Message);
                return View();
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                var registerRequest = new RegisterRequest()
                {
                    Email = model.Email,
                    Password = model.Password,
                    Gender = model.Gender,
                    Name = model.Name,
                    PhoneNumber = model.PhoneNumber,
                    Avatar = model.Avatar
                };
                RegisterResult result = ApiHelper<RegisterResult>.HttpPostAsync($"{Helper.ApiUrl}api/account/register", registerRequest);
                if (result.Success)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", result.Message);
                return View();
            }
            return View(model);
        }

        public IActionResult Logout()
        {
            var result = true;
            return Json(new { result });
        }
    }
}

HotelBooking.WEB/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>@ViewData["Title"]</title>

    <!-- Fontfaces CSS-->
    <link href="~/lib/cooladmin/css/font-face.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/lib/cooladmin/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" />

    <!-- Bootstrap CSS-->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Vendor CSS-->
    <link href="~/lib/cooladmin/vendor/animsition/animsition.min.css" rel="stylesheet" />
    <script src="~/lib/cooladmin/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <link href="~/lib/cooladmin/vendor/wow/animate.css" rel="stylesheet" />
    <link href="~/lib/cooladmin/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" />
    <link href="~/lib/cooladmin/vendor/select2/select2.min.css" rel="stylesheet" />
    <script src="~/lib/cooladmin/vendor/slick/slick.min.js"></script>
    <link href="~/lib/cooladmin/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" />

    <!-- Main CSS-->
    <link href="~/lib/cooladmin/css/theme.css" rel="stylesheet" />
</head>

<body class="animsition">
    <div class="page-wrapper">
        <div class="page-content--bge5">
            <div class="container">
                <div class="login-wrap">
                    <div class="login-content">
                        <div class="login-logo">
                            <a href="#">
                                <img src="~/lib/cooladmin/images/icon/logo.png" alt="CoolAdmin">
                            </a>
                        </div>
                        <div class="login-form">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="~/lib/cooladmin/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="~/lib/cooladmin/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="~/lib/cooladmin/vendor/slick/slick.min.js">
    </script>
    <script src="~/lib/cooladmin/vendor/wow/wow.min.js"></script>
    <script src="~/lib/cooladmin/vendor/animsition/animsition.min.js"></script>
    <script src="~/lib/cooladmin/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js">
    </script>
    <script src="~/lib/cooladmin/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="~/lib/cooladmin/vendor/counter-up/jquery.counterup.min.js">
    </script>
    <script src="~/lib/cooladmin/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="~/lib/cooladmin/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/lib/cooladmin/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="~/lib/cooladmin/vendor/select2/select2.min.js">
    </script>

    <!-- Main JS-->
    <script src="~/lib/cooladmin/js/main.js"></script>
    @RenderSection("scripts", false)
</body>
</html>
<!-- end document-->

HotelBooking.WEB/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="vi">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Hiroto Template">
    <meta name="keywords" content="Hiroto, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewData["Title"]</title>

    <!-- Css Styles -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/hiroto/css/elegant-icons.css" rel="stylesheet" />
    <link href="~/lib/jquery-nice-select/css/nice-select.min.css" rel="stylesheet" />
    <link href="~/lib/jqueryui/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/lib/owl-carousel/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/lib/SlickNav/slicknav.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/hiroto/css/style.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/css/homesite.css" rel="stylesheet" />
    @RenderSection("styles", false)
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__logo">
            <a asp-action="Index" asp-controller="Home"><img src="~/lib/hiroto/img/logo.png" alt=""></a>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="offcanvas__btn__widget">
            <a href="#">Book Now <span class="arrow_right"></span></a>
        </div>
        <div class="offcanvas__widget">
            <ul>
                <li><span class="icon_pin_alt"></span> 34 Võ Thị Sáu, TP.Huế</li>
                <li><span class="icon_phone"></span> +(84) 234.3831358</li>
            </ul>
        </div>
        <div class="offcanvas__auth">
            <ul>
                <li><a asp-controller="User" asp-action="Login" method="get">Đăng nhập</a></li>
                <li><a asp-controller="User" asp-action="Register" method="get">Đăng ký</a></li>
                <li><a asp-controller="RoomTypesManager" asp-action="Index">Dashboard</a></li>
            </ul>
        </div>
    </div>
    <!-- Offcanvas Menu End -->
    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7">
                        <ul class="header__top__widget">
                            <li><span class="icon_pin_alt"></span> 34 Võ Thị Sáu, TP.Huế</li>
                            <li><span class="icon_phone"></span> +(84) 234.3831358</li>
                        </ul>
                    </div>
                    <div class="col-lg-5">
                        <div class="header__top__right">
                            <div class="header__top__auth">
                                <ul>
                                    <li><a asp-controller="User" asp-action="Login" method="get">Đăng nhập</a></li>
                                    <li><a asp-controller="User" asp-action="Register" method="get">Đăng ký</a></li>
                                    <li><a asp-controller="RoomTypesManager" asp-action="Index">Dashboard</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header__nav__option">
            <div class="container">
                <div class="row">
                    <div class="col-lg-2">
                        <div class="header__logo">
                            <a asp-action="Index" asp-controller="Home"><img src="~/lib/hiroto/img/logo.png" alt=""></a>
                        </div>
                    </div>
                    <div class="col-lg-10">
                        <div class="header__nav">
                            <nav class="header__menu">
                                <ul class="menu__class">
                                    <li class="active"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                                    <li><a asp-action="Index" asp-controller="Rooms">Phòng</a></li>
                                    <li><a asp-action="Index" asp-controller="Services">Dịch vụ</a></li>
                                    @*<li><a href="#">Giới thiệu</a></li>
                                        <li><a href="#">Blog</a></li>
                                        <li><a href="#">Liên hệ</a></li>*@
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
                <div class="canvas__open">
                    <span class="fa fa-bars"></span>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

    @RenderBody()

    <!-- Footer Section Begin -->
    <footer class="footer set-bg" data-setbg="/lib/hiroto/img/footer-bg.jpg">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="logo__carousel owl-carousel">
                        <div class="logo__carousel__item">
                            <a href="#"><img src="~/lib/hiroto/img/logo/logo-1.png" alt=""></a>
                        </div>
                        <div class="logo__carousel__item">
                            <a href="#"><img src="~/lib/hiroto/img/logo/logo-2.png" alt=""></a>
                        </div>
                        <div class="logo__carousel__item">
                            <a href="#"><img src="~/lib/hiroto/img/logo/logo-3.png" alt=""></a>
                        </div>
                        <div class="logo__carousel__item">
                            <a href="#"><img src="~/lib/hiroto/img/logo/logo-4.png" alt=""></a>
                        </div>
                        <div class="logo__carousel__item">
                            <a href="#"><img src="~/lib/hiroto/img/logo/logo-5.png" alt=""></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="footer__content">
                <div class="row">
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="footer__about">
                            <div class="footer__logo">
                                <a href="#"><img src="~/lib/hiroto/img/logo.png" alt=""></a>
                            </div>
                            <h4>+(84) 234.3831358</h4>
                            <ul>
                                <li>34 Võ Thị Sáu, Huế</li>
                                <li>goldenstarhuehotel@gmail.com</li>
                            </ul>
                            <div class="footer__social">
                                <a href="#"><i class="fab fa-facebook"></i></a>
                                <a href="#"><i class="fab fa-twitter"></i></a>
                                <a href="#"><i class="fab fa-linkedin"></i></a>
                                <a href="#"><i class="fab fa-youtube"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 offset-lg-1 col-md-5 offset-md-1 col-sm-6">
                        <div class="footer__widget">
                            <h4>Liên kết</h4>
                            <ul>
                                <li class="active"><a asp-action="Index" asp-controller="Home">Trang chủ</a></li>
                                <li><a asp-action="Index" asp-controller="Rooms">Phòng</a></li>
                                <li><a asp-action="Index" asp-controller="Services">Dịch vụ</a></li>
                            </ul>
                            @*<ul>
                                    <li><a href="#">Giới thiệu</a></li>
                                    <li><a href="#">Blog</a></li>
                                    <li><a href="#">Liên hệ</a></li>
                                </ul>*@
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-8 col-sm-12">
                        <div class="footer__newslatter">
                            <h4>Đăng ký nhận tin</h4>
                            <form action="#">
                                <input type="text" placeholder="Địa chỉ Email">
                                <button type="submit">Đăng ký</button>
                            </form>
                            <div class="footer__newslatter__find">
                                <h5>Find Us:</h5>
                                <div class="footer__newslatter__find__links">
                                    <a href="#"><i class="fab fa-tripadvisor"></i></a>
                                    <a href="#"><i class="fa fa-map-marked-alt"></i></a>
                                    <a href="#"><i class="fab fa-dribbble"></i></a>
                                    <a href="#"><i class="fab fa-forumbee"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer__copyright">
                <div class="row">
                    <div class="col-lg-7 col-md-7">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <div class="footer__copyright__text">
                            <p>
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved
                            </p>
                        </div>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                    <div class="col-lg-5 col-md-5">
                        <ul class="footer__copyright__links">
                            <li class="text-light">Developers:</li>
                            <li class="text-light">Trung: <a href="https://github.com/xuantrung48/" target="_blank"><i class="fab fa-github"></i></a> <a href="https://www.facebook.com/XuanTrung/" target="_blank"><i class="fab fa-facebook"></i></a></li>
                            <li class="text-light">Quang: <a href="https://github.com/quangnguyen1235" target="_blank"><i class="fab fa-github"></i></a> <a href="https://www.facebook.com/100003816160398"><i class="fab fa-facebook"></i></a></li>
                            <li class="text-light">Trâm: <a href="https://github.com/lktram1" target="_blank"><i class="fab fa-github"></i></a> <a href="https://www.facebook.com/amaiti.mio/"><i class="fab fa-facebook"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Js Plugins -->
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery-nice-select/js/jquery.nice-select.min.js"></script>
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/SlickNav/jquery.slicknav.min.js"></script>
    <script src="~/lib/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/lib/hiroto/js/main.js"></script>
    <script src="~/lib/js/home/main.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validate1.19.2/jquery.validate.js"></script>
    <script src="~/lib/jquery-validate1.19.2/additional-methods.js"></script>
    @RenderSection("scripts", false)
</body>
</html>